#ifndef VISITOR_H_INCLUDED
#define VISITOR_H_INCLUDED

class CProgramRuleNode;
class CMainClassDeclarationRuleNode;
class CDeclarationsListNode;
class CClassDeclarationRuleNode;
class CExtendDeclarationRuleNode;
class CVarDeclarationsListNode;
class CMethodDeclarationsListNode;
class CVarDeclarationRuleNode;
class CMethodDeclarationRuleNode;
class CVarsDecListNode;
class CVarsDecFirstNode;
class CStatsFirstNode;
class CStatsListNode;
class CMethodBodyVarsNode;
class CMethodBodyStatsNode;
class CMethodBodyAllNode;
class CParamArgListNode;
class CParamsOneNode;
class CParamsTwoNode;
class CParamRuleNode;
class CTypeRuleNode;
class CNumerousStatementsNode;
class CBracedStatementNode;
class CIfStatementNode;
class CWhileStatementNode;
class CPrintStatementNode;
class CAssignStatementNode;
class CInvokeExpressionStatementNode;
class CInvokeExpressionNode;
class CLengthExpressionNode;
class CArithmeticExpressionNode;
class CUnaryExpressionNode;
class CCompareExpressionNode;
class CNotExpressionNode;
class CNewArrayExpressionNode;
class CNewObjectExpressionNode;
class CIntExpressionNode;
class CBooleanExpressionNode;
class CIdentExpressionNode;
class CThisExpressionNode;
class CParenExpressionNode;
class CInvokeMethodExpressionNode;
class CFewArgsExpressionNode;
class CListExpressionNode;
class CLastListExpressionNode;

class CVisitor {
public:
	virtual void Visit(const CProgramRuleNode* node) = 0;
	virtual void Visit(const CMainClassDeclarationRuleNode* node) = 0;
	virtual void Visit(const CDeclarationsListNode* node) = 0;
	virtual void Visit(const CClassDeclarationRuleNode* node) = 0;
	virtual void Visit(const CExtendDeclarationRuleNode* node) = 0;
	virtual void Visit(const CVarDeclarationsListNode* node) = 0;
	virtual void Visit(const CMethodDeclarationsListNode* node) = 0;
	virtual void Visit(const CVarDeclarationRuleNode* node) = 0;
	virtual void Visit(const CMethodDeclarationRuleNode* node) = 0;
	virtual void Visit(const CVarsDecListNode* node) = 0;
	virtual void Visit(const CVarsDecFirstNode* node) = 0;
	virtual void Visit(const CStatsFirstNode* node) = 0;
	virtual void Visit(const CStatsListNode* node) = 0;
	virtual void Visit(const CMethodBodyVarsNode* node) = 0;
	virtual void Visit(const CMethodBodyStatsNode* node) = 0;
	virtual void Visit(const CMethodBodyAllNode* node) = 0;
	virtual void Visit(const CParamArgListNode* node) = 0;
	virtual void Visit(const CParamsOneNode* node) = 0;
	virtual void Visit(const CParamsTwoNode* node) = 0;
	virtual void Visit(const CParamRuleNode* node) = 0;
	virtual void Visit(const CTypeRuleNode* node) = 0;
	virtual void Visit(const CNumerousStatementsNode* node) = 0;
	virtual void Visit(const CBracedStatementNode* node) = 0;
	virtual void Visit(const CIfStatementNode* node) = 0;
	virtual void Visit(const CWhileStatementNode* node) = 0;
	virtual void Visit(const CPrintStatementNode* node) = 0;
	virtual void Visit(const CAssignStatementNode* node) = 0;
	virtual void Visit(const CInvokeExpressionStatementNode* node) = 0;
	virtual void Visit(const CInvokeExpressionNode* node) = 0;
	virtual void Visit(const CLengthExpressionNode* node) = 0;
	virtual void Visit(const CArithmeticExpressionNode* node) = 0;
	virtual void Visit(const CUnaryExpressionNode* node) = 0;
	virtual void Visit(const CCompareExpressionNode* node) = 0;
	virtual void Visit(const CNotExpressionNode* node) = 0;
	virtual void Visit(const CNewArrayExpressionNode* node) = 0;
	virtual void Visit(const CNewObjectExpressionNode* node) = 0;
	virtual void Visit(const CIntExpressionNode* node) = 0;
	virtual void Visit(const CBooleanExpressionNode* node) = 0;
	virtual void Visit(const CIdentExpressionNode* node) = 0;
	virtual void Visit(const CThisExpressionNode* node) = 0;
	virtual void Visit(const CParenExpressionNode* node) = 0;
	virtual void Visit(const CInvokeMethodExpressionNode* node) = 0;
	virtual void Visit(const CFewArgsExpressionNode* node) = 0;
	virtual void Visit(const CListExpressionNode* node) = 0;
	virtual void Visit(const CLastListExpressionNode* node) = 0;
};
#include "../Structs/Ast.h"

#endif
